name: Shell Commands

on: [push]

jobs:
   run-shell-command:
      runs-on: ubuntu-latest
      steps:
        - name: Mudei nome
          run: echho "Hello World"
        - name: mutiline script
          run: |
             node -v
             npm -v
