name: Shell Commands

on: [push]

jobs:
   run-shell-command:
      runs-on: ubuntu-latest
      steps:
        - name: Mudei nome
          run: echo "Hello World"
        - name: mutiline script
          run: |
             node -v
             npm -v
        - name: python Command
          run: |
              import plataform
              print(plataform.processor())
          shell: python


